"use strict";
exports.__esModule = true;
exports.counter = exports.CounterBtn = exports.ApiComp4 = exports.ApiComp3 = exports.ApiComp2 = exports.ApiComp1 = void 0;
var btn_compose_1 = require("./src/counter/btn.compose");
exports.CounterBtn = btn_compose_1["default"];
exports.counter = btn_compose_1.counter;
var api1_comp_1 = require("./src/api1.comp");
exports.ApiComp1 = api1_comp_1.ApiComp1;
var api2_component_1 = require("./src/api2.component");
exports.ApiComp2 = api2_component_1["default"];
var api3_component_1 = require("./src/api3.component");
exports.ApiComp3 = api3_component_1["default"];
var api4_component_1 = require("./src/api4.component");
exports.ApiComp4 = api4_component_1["default"];
